targets:
  $default:
    sources:
      - integration_test/**   # By default, build runner will not generate code in the integration folder
      - test/**               # so we override paths for code generation here
      - lib/**/integration_test/**
      - $package$
    builders:
      bdd_widget_test|featureBuilder:
        options:
          # stepFolderName: bdd_steps
          stepFolderName: step # this trick is required to share steps between widget and integration tests
          # testMethodName: customTestMethodName
        generate_for:
          - test/*.feature
          - integration_test/*.feature
          - lib/**/integration_test/**