name: admin
version: 0.0.2+13
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  decimal: ^1.0.0
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.3
  dio: ^4.0.0
  flutter_bloc: ^7.3.0
  meta: ^1.3.0
  shared_preferences: ^2.0.6
  image_picker: ^0.7.3
  about: ^2.0.0
  animations: ^2.0.0
  responsive_framework: ^0.1.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  printing: ^5.0.4
  pdf: ^3.0.0
  dropdown_search: ^0.6.3
  flutter_phoenix: ^1.0.0
  core:
#    path: ../packages/core
    git:
      url: https://github.com/growerp/growerp.git
      ref: packages
      path: core
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  bdd_widget_test: ^1.2.0     
  utils:
#    path: ../packages/utils
    git:
      url: https://github.com/growerp/growerp.git
      ref: packages
      path: utils

  mockito: ^5.0.2
  very_good_analysis: ^2.0.0

  bloc_test: ^8.2.0
  flutter_launcher_icons: ^0.9.0
# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/growerp.jpg"

flutter:
  uses-material-design: true
  # from https://www.flaticon.com/
  assets:
    - assets/images/
    - assets/cfg/
    - ./
    - packages/core/images/info.png
    - packages/core/images/infoGrey.png
    - packages/core/images/chat.png
    - packages/core/images/chatGrey.png
flutter_intl:
  enabled: true
