name: admin
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.6.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  decimal: ^0.3.0
  global_configuration: ^1.6.0
  equatable: ^1.2.5
  dio: ^3.0.9
  flutter_bloc: ^6.1.0
  meta: ^1.1.6
  shared_preferences: ^0.5.12+2
  image_picker: ^0.6.7+17
  image_picker_for_web: ^0.1.0+2
  about: ^1.1.2
  animations: ^1.0.0+5
  responsive_framework: ^0.0.8
  printing: ^3.7.1
  core:
#    path: ../packages/core
    git:
      url: https://github.com/growerp/growerp.git
      ref: packages
      path: core
#  models:
#    path: ../packages/models
#    git:
#      url: https://github.com/growerp/growerp.git
#      ref: packages
#      path: models

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.5.0
  bloc_test: ^7.1.0
  flutter_launcher_icons: ^0.8.1
# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/growerp.jpg"

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
  assets:
    - assets/images/
    - assets/cfg/
    - ./