name: admin
version: 0.0.2+13
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  core:
    path: ../core/
  decimal: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
        sdk: flutter
  flutter_phoenix: ^1.0.0
  global_configuration: ^2.0.0-nullsafety.0
  intl: ^0.17.0
  printing: ^5.0.4
  responsive_framework: ^0.1.0
  shared_preferences: ^2.0.6

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  utils:
    path: ../utils/

#  flutter_icons:
#    android: "launcher_icon"
#    ios: true
#    image_path: "assets/images/growerp.jpg"
# to run icons: flutter pub run flutter_launcher_icons:main 


flutter:
  uses-material-design: true
  # from https://www.flaticon.com/
  assets:
    - assets/images/
    - assets/cfg/
    - ./
    - packages/core/images/info.png
    - packages/core/images/infoGrey.png
    - packages/core/images/chat.png
    - packages/core/images/chatGrey.png
flutter_intl:
  enabled: true
